heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server with an Ansible
  deployment


parameters:

  server_hostname:
    label: Server Name
    description: Hostname to use for setting the server name.
    type: string
    default: web
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Server Image
    description: Operating system to use for the Linux Server
    type: string
    default: CentOS 6.5

  flavor:
    label: Cloud Server flavor
    description: Flavor of Cloud server to use
    type: string
    default: 1 GB Performance

  ssh_keypair_name:
    label: SSH Keypair Name
    description: New nova keypair name for ssh access to the server
    type: string
    constraints:
    - allowed_pattern: "^(.){1,64}$"
      description: "Must be shorter than 64 characters or fewer."

  kitchen:
    description: URL for the kitchen to use
    type: string
    default: https://github.com/cmecca/ChefAnsibleWrapper

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.12.2

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  linux_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }

  linux_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: linux_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [linux_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        run_list: ["recipe[testansible]"]


outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    value: { get_attr: [linux_server, accessIPv4] }
