---

- name: Install MySQL packages on Ubuntu base
  apt: name={{item}} state=present
  with_items: 
  - libmysqlclient15-dev
  - mysql-client
  when: ansible_distribution == "Ubuntu"

- name: Install MySQL packages on Debian base
  apt: name={{item}} state=present
  with_items:
  - libmysqlclient-dev
  - mysql-client
  when: ansible_distribution == "Debian"


