---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Check for existing seed file
  command: test -f /var/cache/local/preseeding/mysql-server.seed
  when: ansible_os_family == "Debian"
  register: seed_found
  ignore_errors: yes

- name: Add preseeding folder to Debian base
  file: path=/var/cache/local/preseeding owner=root group=root state=directory
  when: ansible_os_family == "Debian" and seed_found.rc !=0

- name: Add debian.cnf
  template: src=debian.cnf.j2 dest=/etc/mysql/debian.cnf
  when: ansible_os_family == "Debian" and seed_found.rc !=0

- name: Add pre-seed template to Debian base
  template: src=mysql-server.seed.j2 dest=/var/cache/local/preseeding/mysql-server.seed
  when: ansible_os_family == "Debian" and seed_found.rc !=0
  register: seed

- name: Seed MySQL
  command: /usr/bin/debconf-set-selections /var/cache/local/preseeding/mysql-server.seed
  when: ansible_os_family == "Debian" and seed|changed
