---

- name: Install varnish repo for RedHat/CentOS 6
  yum: name=http://repo.varnish-cache.org/redhat/varnish-3.0/el6/noarch/varnish-release/varnish-release-3.0-1.el6.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 7

- name: Install varnish on RedHat base
  yum: name=varnish state=present
  when: ansible_os_family == 'RedHat'

- name: Install varnish packages on Ubuntu base
  apt: name={{item}} state=present
  with_items:
    - varnish
    - libvarnishapi1
  when: ansible_os_family == 'Debian'

- name: Move existing varnish config
  command: mv -f /etc/varnish/default.vcl /etc/varnish/default.vcl.orig

- name: Download new varnish config for RedHat base
  get_url:
    url: http://c460059.r59.cf2.rackcdn.com/cent_default4.vcl
    dest: /etc/varnish/default.vcl
  when: ansible_os_family == 'RedHat'

- name: Download new varnish config for Debian base
  get_url:
    url: http://c460059.r59.cf2.rackcdn.com/ubu_default.vcl
    dest: /etc/varnish/default.vcl
  when: ansible_os_family == 'Debian'

- name: Fix varnish config for Client IP and X-Forwarded-For
  command: sed -i 's/req.http.X-Forwarded-For  ", "  client.ip;$/req.http.X-Forwarded-For + ", " + client.ip;/' /etc/varnish/default.vcl

- name: Fix varnish config for Server IP and X-Forwarded-Host
  command: sed -i 's/req.http.X-Forwarded-Host ", " server.ip;$/req.http.X-Forwarded-Host + ", " + server.ip;/' /etc/varnish/default.vcl
  when: ansible_os_family == 'Debian'

- name: Set port 80 as the backend default port
  command: sed -i 's/"8080";/":80";/' /etc/varnish/default.vcl

- name: Enable and restart the varnish service
  service: name=lsyncd state=restarted enabled=yes

- name: Copy wordpress vcl to varnish directory for varnish 3
  template: src=wordpress_varn3.vcl.j2 dest=/etc/varnish/wordpress_varn3.vcl

- name: Copy wordpress vcl to varnish directory for varnish 4
  template: src=wordpress_varn4.vcl.j2 dest=/etc/varnish.wordpress_varn4.vcl
