---
- hosts: all
  user: root

  tasks:
    - group_by: key={{ ansible_os_family }}
#      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]


- hosts: RedHat
  user: root

  pre_tasks:
    - name: install LSB_release req for RHEL systems
      yum: pkg=redhat-lsb state=installed
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]
    
    - name: regather facts
      setup:
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

    - include_vars: group_vars/RHEL_7.yml
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '7'
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

  roles:
    - { role: IUS-repos, tags: ius-repos, when: ansible_os_family == 'RedHat'}
    - { role: apache2, tags: apache2 }
    - { role: php5, tags: php5 }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: holland, tags: holland }


- hosts: Debian
  user: root

#  pre_tasks:
#    - include_vars: group_vars/Ubuntu_14.yml
#      when: ansible_os_family == 'Debian' and ansible_lsb.major_release == '14.04'
#      tags: [ 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

  roles:
    - { role: apache2, tags: apache2 }
    - { role: php5, tags: php5 }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: holland, tags: holland }

