---
- hosts: all
  user: root

  pre_tasks:
    - name: install LSB_release req for RHEL systems
      yum: pkg=redhat-lsb state=installed
      when: ansible_os_family == 'RedHat'
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]
#      tags: all
    
    - name: regather facts
      setup:
      when: ansible_os_family == 'RedHat'
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

    - group_by: key={{ ansible_os_family }}
      tags: [ 'ius-repos', 'apache2', 'php5', 'mysql', 'phpmyadmin', 'holland' ]

    - add_host: name={{ansible_nodename}} groups=RedHat_7
      when: ansible_os_family == 'RedHat' and ansible_lsb.major_release == '7'

  roles:
    - { role: IUS-repos, tags: ius-repos when: ansible_os_family == 'RedHat'}
    - { role: apache2, tags: apache2 }
    - { role: php5, tags: php5 }
    - { role: mysql, tags: mysql }
    - { role: phpmyadmin, tags: phpmyadmin }
    - { role: holland, tags: holland }
